import type { RemediationPlan } from "./plan.js";

/**
 * npm `overrides` block, ready to paste into package.json.
 *
 * Only emitted when the caller supplied the malicious versions, because a pin
 * needs a known-good target. Inventing one would produce a patch that looks
 * authoritative and is not, which is worse than no patch: it would be applied
 * without reading. When versions are unknown the caller gets an explicit gap
 * instead.
 */
export function renderOverrides(
  plan: RemediationPlan,
  safeVersion?: string,
): { applicable: boolean; content: string; note: string } {
  if (!safeVersion) {
    return {
      applicable: false,
      content: "",
      note:
        `No safe version supplied for ${plan.compromised}, so no override was ` +
        `generated. Re-run with --safe-version <version> once the advisory ` +
        `names a clean release. HyperDefense will not guess a pin.`,
    };
  }

  const overrides = { [plan.compromised]: safeVersion };
  return {
    applicable: true,
    content: `${JSON.stringify({ overrides }, null, 2)}\n`,
    note:
      `Merge the "overrides" key into package.json, then reinstall. This forces ` +
      `every transitive resolution of ${plan.compromised} to ${safeVersion}, ` +
      `including the ${plan.counts.downstream} downstream package(s) that pull it in.`,
  };
}

/**
 * A GitHub Actions job that fails the build if a blocked package resolves.
 *
 * This is the point of the whole exercise: the finding has to live where the
 * work already happens. A report someone has to remember to read is not a
 * control; a required check that fails the PR is.
 */
export function renderWorkflow(plan: RemediationPlan): string {
  return `# Generated by HyperDefense for the ${plan.compromised} compromise.
# Fails the build if a blocked package version resolves in the lockfile.
name: supply-chain-gate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  blocklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install HyperDefense
        run: npm ci
      - name: Build
        # The 'hyperdefense' bin resolves to dist/, so the CLI must be compiled
        # before it can be invoked. Without this the gate fails to start, which
        # would look like a passing build in a workflow that never ran.
        run: npm run build
      - name: Enforce supply-chain blocklist
        # Exits 1 when a blocked package version resolved, failing the check and
        # blocking the merge. Exit 2 means the gate could not run at all, which
        # also fails rather than being mistaken for a pass.
        run: npx hyperdefense verify --blocklist .hyperdefense/blocklist.json
`;
}

/** Human-readable summary for a PR comment or terminal. */
export function renderSummary(plan: RemediationPlan): string {
  const lines: string[] = [
    `Supply chain exposure: ${plan.compromised}`,
    "",
    `- confirmed compromised: ${plan.compromised}`,
    `- resolves the bad code (${plan.counts.downstream}): ${
      plan.entries
        .filter((e) => e.reason === "downstream")
        .map((e) => e.name)
        .join(", ") || "none in graph"
    }`,
    `- reachable via shared maintainer (${plan.counts.sharedMaintainer}): ${
      plan.entries
        .filter((e) => e.reason === "shared-maintainer")
        .map((e) => e.name)
        .join(", ") || "none"
    }`,
    "",
    `A dependency-only scanner reports ${plan.counts.downstream} affected package(s).`,
    `Including maintainer reach, ${
      plan.counts.downstream + plan.counts.sharedMaintainer
    } need review.`,
  ];
  return `${lines.join("\n")}\n`;
}
